language: objective-c
osx_image: xcode10.2
env:
  - SWIFT_VERSION=4.0
  - SWIFT_VERSION=4.2
  - SWIFT_VERSION=5.0
install:
  - bundle install
  - brew outdated carthage || brew upgrade carthage
before_script:
  - bundle exec pod lib lint --verbose --fail-fast
  - carthage build --verbose --no-skip-current
script:
  - xcodebuild -project AloeStackView.xcodeproj -scheme AloeStackView -sdk iphonesimulator -destination "platform=iOS Simulator,OS=10.0,name=iPhone 6s" -configuration Debug -PBXBuildsContinueAfterErrors=0 SWIFT_VERSION=$SWIFT_VERSION build test
